### ISSUE TITLE
Hi! Can you help me?

### ISSUE THREAD

**Issue by epriwahyu** [ankit61/cough-detection#2]
I am taking Data Science and Practice class, how to run your cough detection program? I am so new about this T.T. Can I use windows or Linux? Thanks

**Comment by ankit61** [comment]
Hi Epri! I have tested this code on Linux, but I think you could use Windows if you really want by running [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) on Windows. However, I'd recommend using Linux (because I anticipate that there may be some issues on Windows).

As far as how to run is concerned, please follow the "Instructions to run" section on the [README](https://github.com/ankit61/cough-detection/blob/master/README.md). Simply execute those commands in your terminal and your environment will be set up.

Please also watch [this](https://youtu.be/lbWrVA05pJo) video which explains how to exactly run the code. 

Please feel free to ask more questions if you get stuck.

**Comment by ankit61** [comment]
Also, please note that this is a work in development. So, I may later add some improvements to the model/code. If you do not want further improvements and like how the project is at this state, please fork the repo so you can get the repo at this stage

**Comment by epriwahyu** [comment]
Hi Ankit61,

Thanks a lot for fast reply. I will do my best. If I have problems, I will ask you again. 

Thanks

**Comment by ankit61** [comment]
Sure! Closing issue for now, feel free to reopen in case of issues
